services:
    postgresql:
        image: postgres:15
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
            TZ: 'Asia/Seoul'
    redis:
        image: redis:7.2-alpine
        restart: always
        volumes:
            - redisdata:/var/lib/redis/data
        ports:
            - 6379:6379

volumes:
    pgdata:
        external: false
    redisdata:
        external: false
